### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jtannenba** [Jyers/Marlin#1382]
Would it be possible to enable the z-offset wizard?  If it is set, don't see it on my E3V2 with 4.2.7 mainboard.
Thank you

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by tititopher68-dev** [comment]
@jtannenba
To answer this  simply, PROBE_OFFSET_WIZARD and such are not currently used by the firmware, because the Display DWIN for Ender3V2 isn't for Marlin a LCD 12864 Display (like Ender 3 V1). This function requires the use of this type of LCD 12864 screen.
The way in which the Z-Offset setting is implemented does not require this functionality at all.

**Comment by jtannenba** [comment]
Thank you
