### ISSUE TITLE
Filament Change

### ISSUE THREAD

**Issue by Grenalis** [Jyers/Marlin#1417]
When doing a filament change, (in firmware), upon resuming, the X and or Y axis will slam in one direction, then the print will continue, approx. 5mm off where it should be on the Y axis.  This has happened a the last 2 times I did a filament change, of course requiring a restart of print without a filament change.  

### Steps to Reproduce

1. Select Tune
2. Select Filament Change
3. Follow instructions
4. Cancel purge
5. Bed or Extruder will slam in one direction

**Expected behavior:** [Continue to print]

**Actual behavior:** [X and or Y slams.  Print now off by 5mm on Y axis]

#### Additional Information

* Include a ZIP file containing your `Configuration.h` and `Configuration_adv.h` files.
* Provide pictures or links to videos that clearly demonstrate the issue.
* See [How Can I Contribute](#how-can-i-contribute) for additional guidelines.

**Comment by tititopher68-dev** [comment]
@Grenalis 
Can you more accurate on the firmware version used, configuration files, etc.?
For several months, this Bug Marlin no longer exists, including in the Jyers's Firmware ...
This can not be a firmware issue, because the GCODE M600 is not modified by Jyers and is part of the common sources of Marlin ...

**Comment by tititopher68-dev** [comment]
@Grenalis 
And see #1395

**Comment by Grenalis** [comment]
The current E3V2-BLTouch-5x5-HS-v4.2.7-v1.3.5.b .  Happened both times I did a filament change via firmware.  Not using any specific config files.  Just the firmware.  Also I am using Cura 4.11

**Comment by tititopher68-dev** [comment]
@Grenalis 
But sorry, no firmware issue.  Filament change is managed in the firmware by the call to a Gcode M600 ... which has not been modified by Jyers and which has been coded by Marlin for all printers.
And as for @DJWonderfull, in the end no issue.  I just did it and no issue.
I take this opportunity to remind you that you have to compile your own firmware from the build and the latest commits here.  The Version 1.3.5.b is old (there have been no precompiled firmwares since ... Jyers being very busy with his move and reinstallation).
Another important thing, you must always after flashing the firmware, do a Reset to Default, following by a Store settings and following by a Load settings ...

**Comment by tititopher68-dev** [comment]
@Grenalis 
Perhaps your issue is a Cura issue. Try if you can PrusaSlicer...

**Comment by Grenalis** [comment]
@tititopher68-dev 
What is the newest Jyers if 1.3.5b is old?  On Jyers git is says Aug 10 for 1.3.5b
I will try a filament change in cura.  I have always did it in the past via interface on printer... ie firmware

**Comment by Jyers** [comment]
I'm going to close this as it seems to be an individual case. If you still have the issue I'd recommend trying the latest source when I next make a release (soon) and see if that helps
