### ISSUE TITLE
Resume print after power loss not working as expected.

### ISSUE THREAD

**Issue by Coo902418** [Jyers/Marlin#1954]
Description:
When I resumed a print after power off the printer raised about 10mm off the print then started printing in air.

Steps to Reproduce
First Step:
  Pause printer during a print

Second Step:
  Turned off power at main switch

Third Step: 
  Turned on printer some hours later

Fourth Step:
  Clicked confirm to resume print

Expected behavior: Printing resumes at last height

Actual behavior: z axis raised approx 10mm off print height and then resumed print.

Additional Information
Board: 4.2.2
Firmware: E3V2-ManualMesh-3x3-v4.2.2-v2.0.1
Ender 3 v2 stock hardware<!--

**Comment by tititopher68-dev** [comment]
@Coo902418 
Not a firmware issue, just a bad writing on the SD of the necessary information, it sometimes happens if the SD starts to fail...For information, only the Marlin code manages the Power Less Recovery! Not the UI code from Jyers. And no report of your issue in the GitHub Marlin!

If you want an update version of JyersUI project, you can take a look at : https://github.com/tititopher68-dev2/Marlin/tree/new_feature (the last build and continuation of the very beautiful Jyers Project of which I took over the development)

**Comment by Coo902418** [comment]
Thanks, thought it could have been the firmware as It didn't happen until after I updated.
