### ISSUE TITLE
Manual mesh 3 x 3 fan cooling changes value

### ISSUE THREAD

**Issue by PossibleCause** [Jyers/Marlin#482]
Hi,

I installed the manual mesh 3 x 3 recently for 4.2.2. Board. I have an issue with layer shifting because the board is not cooled enough by the fan. I discovered that the fan that cools the board is turned off. When I change it back in tune menu to value 255 it speeds up again but then after a while it changes to value 85 and more later to 175. Why is this hapening. I need the fan to run at all times on value 255 otherwise the steppermotors get to hot and layer shifting starts to happen. This occured after I executed the Autotune PID for the bed and hotend. 

What could be the issue here. Is there a solution for this problem?

**Comment by morpheus4hirez** [comment]
The part cooling fan and fan for the main board work together. So when the part cooling fan is off so is the main board fan. You can wire the main board fan directly to 24V power on the main board so it will be on constantly. This is working as intended with your setup and I suspect the fan changing speeds while printing has to do with your slicer settings rather than this firmware. Try changing your cooling settings in your slicer to have a max fan speed at first layer if you don't want to wire the main board fan directly to the main board.
