### ISSUE TITLE
Probe releasing too fast for second measurement

### ISSUE THREAD

**Issue by f-zappa** [Jyers/Marlin#531]
Installed this firmware yesterday and already love it, but I found one problem with my BLtouch (clone). When dual-probing, the probe is released when the head is still very close to the bed, making the probe hitting the bed. This might destroy the sensor after some time. Behaviour was different with my old, self-compiled firmware, I compared the configs but I couldn't figure out which setting is responsible for this effect.
I made a slow-motion-video showing the problem.

**Comment by f-zappa** [comment]
https://user-images.githubusercontent.com/43571251/115149957-a0370200-a066-11eb-887c-9ddc41111d01.mov

**Comment by aryajuanda** [comment]
<img width="805" alt="Screen Shot 2021-04-19 at 04 24 11" src="https://user-images.githubusercontent.com/4106760/115161317-37cc3d00-a0c7-11eb-9b08-8b44cdc64d8a.png">

you can set the clearance here...

**Comment by Jyers** [comment]
Let me know if @aryajuanda solution works. If not I can assist in looking for another potential fix.

**Comment by f-zappa** [comment]
I changed this values to 15/10/10, but the behaviour is still the same.

```
#define Z_CLEARANCE_DEPLOY_PROBE    15 // Z Clearance for Deploy/Stow
#define Z_CLEARANCE_BETWEEN_PROBES  10 // Z Clearance between probe points
#define Z_CLEARANCE_MULTI_PROBE     10 // Z Clearance between multiple probes
```
Any other ideas?

**Comment by aryajuanda** [comment]
mmm i have no idea.. i m not using normal mode, i use HS (High Speed) mode so my probe nozzle did not push in n out each time..

**Comment by foxylion** [comment]
I'm having similar issues with the `E3V2-UBL-BLTouch-10x10-v4.2.2.bin` variant of the latest release.

When letting the printer create the mesh some probes will fail because the second measurement fails due to the probe going into ALARM mode.

So what happens in detail is:

1.  probe deploys for the first time
2.  probe triggers after z was decreased enough
3.  probe is deployed for the second time
4.  probe directly hits the build plate, because z was not already increased enough
5.  probe directly tries a second time to deploy (only a few ms in between), this again fails
6.  probe "retracts" and goes into alarm state
7.  build plate is lowered until it hits the Z stop
8.  a value that is completely off is stored in the mesh

_Before I moved the z stop again into place as an emergency stop the print head hit the build plate twice (due to this issue)._

I don't think that increasing the move of Z does help in any way, because the problem is only that it has not yet traveled _enough_ when the probe deploys the second time.

Is there any option to delay the second deploy for a few more milliseconds? I think that would fix the problem.

Is it possible to get the exact same configuration files you (@Jyers) used for building `E3V2-UBL-BLTouch-10x10-v4.2.2.bin`?

**Comment by foxylion** [comment]
Okay it looks like I found the option that solves the problem for me:
In `Configuration_adv.h` uncomment `#define BLTOUCH_DELAY 500`.

This delays the re-deploy of the BL Touch for 500 ms after every trigger.
This gives the print head enough time to move enough upwards.

Maybe this should be the default? Not doing it won't speed up the process because moving Z up for 5 mm between probes will take approx. the same time.

**Comment by Jyers** [comment]
@foxylion Thanks for finding that! This seams to only be an issue with BL Touch clones, but I'll looking into making that the default. I just need to check if it impacts high speed mode strangely as in that mode it doesn't retract between probes.
