### ISSUE TITLE
Filament Change "Please wait for prompt" after unloading and loading filament does not go away

### ISSUE THREAD

**Issue by nullstalgia** [Jyers/Marlin#744]
Only tested with the Change Filament button in Prepare, just started with the latest changes.

Config:

https://gist.github.com/nullstalgia/ffc9f56772b4032f4bf2bcd7a3562951

**Comment by tititopher68** [comment]
I confirm.  There is a problem on the latest version since the last Merge Marlin with Filament Change, Load or Unload filament (stay on the popup) and with Runout (no longer resumes printing after loading filament) ...

**Comment by xantrk** [comment]
I confirm, just entered to write this

**Comment by tititopher68** [comment]
I think I found it. The problem is at pause.cpp (src \ feature \) with M600_PURGE_MORE_RESUMABLE. This variable is defined in inc / Conditionnals_post.h. For us, 2 conditions are valid: EMERGENCY_PARSER && HOST_PROMPT_SUPPORT. This results in waiting for a user action that is not defined in the firmware, that of being able to interrupt the purge at the end of the procedure ...

**Comment by tititopher68** [comment]
Fixed !
I replaced in file \Marlin\src\inc\Conditionnals_post.h 
in line 2728 
#if HAS_LCD_MENU || BOTH(EMERGENCY_PARSER, HOST_PROMPT_SUPPORT
by : 
#if (HAS_LCD_MENU || BOTH(EMERGENCY_PARSER, HOST_PROMPT_SUPPORT)) && DISABLED(CREALITY_DWIN_EXTUI)

**Comment by Jyers** [comment]
This seems like a good excuse for me to actually implement the extra purge system that's causing the issue here. That way it'll fix the problem AND add a new feature :) Now that's some efficiency.

**Comment by tititopher68** [comment]
I didn't quite understand what you mean.  The translation tells me that you leave the bug for the moment and that you will implement a fix later?
 I had an idea for that, but implementing this possibility requires modifying pause.h and pause.cpp a little more in depth.  I considered it best not to touch the Marlin source code too much ... Am I wrong?

**Comment by nullstalgia** [comment]
@tititopher68 

He will both add a new feature and fix the bug soon. :)

And yes, you are right in wanting to avoid touching Marlin source as much as possible.

**Comment by tititopher68** [comment]
@nullstalgia Yes, but while waiting for, the bug affects too many functionalities, not only the loads or changes of Filament but also all the M600 commands in the print or the pause or even the filament cuts ... The fix that I propose follows the logic of the  Marlin code in pause.cpp.  Moreover this bug exists for other types of screen like BTT TFT etc ... and as the stock version does not support this function via the screen, this may explain why Marlin did not go further in the  reflection ... and in the Marlin code, this MORE PURGE function is only written for LCD screens like those of CR10 or Ender3 V1.  And nothing for the rest ...

**Comment by tititopher68** [comment]
Jyers makes the choices he wants, no problem.  In the meantime I use the fix to not be blocked or have to destroy prints of several hours because of this bug ...

**Comment by Jyers** [comment]
@tititopher68 This bug shouldn't exist for any other screens, it is purely due to the handling of the function via the DWIN code. I really need to update the dwin to a more MarlinUI centric approach, This in tern will not only fix the issue, but do so without any modification of the pause.cpp code. As for delaying the fix, that's the magic of github, you don't need to use the latest source, you can use the last stable release or somewhere in between. People understand the the source is in active development and therefore will occasionally have a bug for a bit before it's fixed.

**Comment by Jyers** [comment]
Done, give that a try! 😄

**Comment by tititopher68** [comment]
@Jyers 
Well done !

**Comment by Jyers** [comment]
@tititopher68 Thanks! I tried to avoid too much main code modification, while opening up the new marlinUI method for future integrations. Thanks for your work as always 😄
