### ISSUE TITLE
Mesh bed levelling = compile error

### ISSUE THREAD

**Issue by enderextender** [Jyers/Marlin#840]
### Description

Uncomment #MESH_BED_LEVELLING
Compile
Results in
Marlin\src\lcd\dwin\creality_dwin.cpp:257:35: error: 'z_values' was not declared in this scope
       bed_mesh_t &mesh_z_values = z_values;

### Steps to Reproduce

1. Uncomment #MESH_BED_LEVELLING
2. Compile

**Expected behavior:** [What you expect to happen]
Should compile ok

**Actual behavior:** [What actually happens]
Error
Marlin\src\lcd\dwin\creality_dwin.cpp:257:35: error: 'z_values' was not declared in this scope
       bed_mesh_t &mesh_z_values = z_values;

#### Additional Information

Using stock zip file from default branch, no other changes other than the above.

**Comment by Jyers** [comment]
This firmware isn't designed to be used with the MESH_BED_LEVELING option. I would recommend starting with the ManualMesh template configs from the configuration files folder if you wish to compile a Manual Mesh build. In case you're interested, instead of MESH_BED_LEVELING, this firmware uses AUTO_BED_LEVELING_BILINEAR with PROBE_MANUALLY
